name: CI

on: [push, pull_request]

jobs:
  checkout:
    runs-on: ubuntu-latest
    uses: actions/checkout@v1
    steps:
    - name: Checkout
      run: echo Code checkout got executed.
  setup:
    needs: checkout
    steps:
    - name: Setup
      run: |
        yarn install
        yarn lint