name: CI

on: [push, pull_request]

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
    uses: actions/checkout@v1
  setup:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
    - name: Setup
      run: |
        yarn install
        yarn lint
  test:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
    - name: Test
      run: yarn test