name: CI

on: [push, pull_request]

jobs:
  checkout:
    runs-on: ubuntu-latest
    uses: actions/checkout@v1
    steps:
    - run: echo Code checkout got executed.
  setup:
    needs: checkout
    steps:
    - run: |
      yarn install
      yarn lint