name: CI

on: [push, pull_request]

jobs:
  setup:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
    - name: Setup
      uses: actions/checkout@v1
      run: |
        yarn install
        yarn lint
  test:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
    - name: Test
      uses: actions/checkout@v1
      run: yarn test