name: pr

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run yarn lint
        run: |
          yarn install
          yarn lint
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run yarn test
        run: |
          yarn install
          yarn test
  test:e2e:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - uses: expo/expo-github-action@v5
        with:
          expo-version: 3.x
          expo-cache: true
      - name: Install applesimutils
        run: |
          brew tap wix/brew
          brew install applesimutils
      - run: yarn install
      - name: Download ExpoClient binary
        run: ./e2e/dl_expo_bins.sh
      - name: Run E2E Tests
        run: |
          # Start packager in background
          yarn start >/dev/null &
          PID=$(ps $! | tail -1 | awk '{print $1}')
          # Run e2e test
          yarn test:e2e
          # Kill packager
          kill $PID
      - uses: actions/upload-artifact@master
        with:
          name: e2e-artifacts
          path: ./artifacts
